# Generated by Django 4.2.2 on 2023-06-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
